### PR TITLE
Pythagorus triplet

### PR DESCRIPTION
**Pull request by TanujRohilla**
Program for Pythgorus triplet

### CODE REVIEW

**Comment by tavishjain** [comment]
Can you tell me the question number and chapter it is associated with ?

**Comment by TanujRohilla** [comment]
> Can you tell me the question number and chapter it is associated with ?

This question is asked by many company, I have solved this is queestion when I am preparing for interview. Please remove Invalid

**Comment by TanujRohilla** [comment]
> Can you tell me the question number and chapter it is associated with ?

If you are not familier look
https://practice.geeksforgeeks.org/problems/pythagorean-triplet/0

**Comment by tavishjain** [comment]
This repo is not for Interview questions. It is for solutions to the book *Cracking the Coding Interview* only

**Comment by TanujRohilla** [comment]
> This repo is not for Interview questions. It is for solutions to the book _Cracking the Coding Interview_ only

sorry for that , you should ignore by PR, please remove Invalid label that you marked, becos this is my first time i am contributing giving negative impact in HacktoberFest

**Comment by tavishjain** [comment]
image
You have 191 contributions in the past year in various different repos. I dont think this is your first time

**Comment by tavishjain** [comment]
At least say things that are not verifiable 

Even lying is an art man

**Pull request closed without merging**
